### ISSUE TITLE
How does this compare with the design of other Erlang HTTP libraries?

### ISSUE THREAD

**Issue by novabyte** [knutin/party#4]
I'm interested to understand how the design of this client differs from [Fusco](https://github.com/esl/fusco) or [Hackney](https://github.com/benoitc/hackney).

What tradeoffs have you made to reach certain performance targets? Do you have plans to add performance instrumentation and/or request tracing to the client?

**Comment by knutin** [comment]
Party is intended to work well for the cases where you have long-lived connections to a few hosts, such an S3, Riak, DynamoDB or other HTTP services and you want to get as much throughput out of your servers as is possible. Party will try to keep a bunch of connections alive and balance the requests over these connections. There's an upper bound on the number of connections (configured by the user) to not overload the endpoint.

The party HTTP client was mainly born from frustration with the connection pooling mechanism in lhttpc, httpc, etc. These all use a single process that manages the connections. Clients asks to check out a connection from this process, does the request, then checks the connection back in. Party was an experiment to see if it was possible to remove this single process bottleneck and instead make it truly parallel.

Party uses a pooling library called carpool which is based on ETS primitives and clever hacks to try to make it parallel. Unfortunately, I discovered after basing my implementation on an ETS table of type ordered_set, that it does not allow parallel reads and writes as with the other table types. It's still pretty fast, although rewriting it would probably give big gains on machines with many cores.

Party also uses binaries for strings instead of lists.

I was unaware of Fusco until you mentioned it now, so I can't really comment to the differences.

I don't have any immediate plans for how to take this project further. In the coming months I'll need it in a new project which would be a great chance for some polish, maybe enough to take it out of "experimental" state. Party is used in production today at Game Analytics.

**Comment by novabyte** [comment]
OK, thanks.
